name: actions-downloads-artifacts-issue

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow_ref, github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  upload-artifacts:
    name: upload artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

    steps:
      - run: |
          RANDOM=${{ matrix.id }}
          for _ in {1..100}
          do
            echo $RANDOM >> file
          done
          sha256sum data > file.${{ matrix.id }}.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: file-${{ matrix.id }}
          path: file
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: hash-${{ matrix.id }}
          path: file.*.sha256
          if-no-files-found: error

  download-artifacts:
    name: download artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.2.1
        with:
          name: file-*
          path: file/
          merge-multiple: true

      - uses: actions/download-artifact@v4.2.1
        with:
          name: hash-*
          path: hash-files/
          merge-multiple: true

      - run: |
          cat hash-files/* > hashes
          DOWNLOADED_FILE_HASH=$(sha256sum file/file | cut -d ' ' -f 1)
          echo "looking for downloaded file hash: ${DOWNLOADED_FILE_HASH}"
          grep "${DOWNLOADED_FILE_HASH}" hashes

      - run: |
          cat hashes
